version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6-jdk-12
    steps:
      - checkout
      - run:
          name: Build and Unit tests
          command: 'mvn clean verify'
      - store_test_results
